package yuda;
import java.text.NumberFormat;
import java.util.Locale;
public class Pesawat extends javax.swing.JFrame {
    int total;
    int totalhar;
    int jumbel;
    int multi;
    double diskon;
    double totalbayar;
    double hk;
    double discont;
    double ttldsc;
    double hs;
    public Pesawat() {
        initComponents();
        int multi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtroute = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txthargatiket = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtjumbel = new javax.swing.JTextField();
        pesawat = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtjumhar = new javax.swing.JTextField();
        sejalan = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        pp = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotalhart = new javax.swing.JTextField();
        btnjumlah = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cash = new javax.swing.JRadioButton();
        kredit = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        potbayar = new javax.swing.JTextField();
        ttlharga = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jadwal Penerbangan Peswat");

        jLabel2.setText("Bandara Soekarno-Hatta");

        jLabel3.setText("Route");

        jLabel4.setText("Harga Tiket");

        jLabel5.setText("Jumlah Beli");

        txtjumbel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumbelActionPerformed(evt);
            }
        });

        pesawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih", "Garuda", "Merpati", "Mandala", "Lion", "Sempati" }));
        pesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesawatActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama Pesawat");

        jLabel7.setText("Jumlah Harga");

        buttonGroup1.add(sejalan);
        sejalan.setText("Sejalan");
        sejalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sejalanActionPerformed(evt);
            }
        });

        jLabel8.setText("Jenis Perjalanan");

        buttonGroup1.add(pp);
        pp.setText("Pulang Pergi");
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });

        jLabel9.setText("Diskon");

        jLabel10.setText("Total Harga Yang Harus Dibayar");

        btnjumlah.setText("Jumlah Harga");
        btnjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjumlahActionPerformed(evt);
            }
        });

        btntotal.setText("Total ");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        jLabel11.setText("Metode Pembayaran");

        buttonGroup2.add(cash);
        cash.setText("Cash");

        buttonGroup2.add(kredit);
        kredit.setText("Kredit");

        jLabel12.setText("Total harga Tiket");

        jLabel13.setText("Potongan pembayaran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addGap(212, 212, 212))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnjumlah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(btntotal)
                                .addGap(55, 55, 55)
                                .addComponent(btnhapus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(93, 93, 93)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkeluar)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kredit)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(cash))
                                                .addGap(154, 154, 154)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(potbayar)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addGap(0, 33, Short.MAX_VALUE))
                                                    .addComponent(ttlharga)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(txtroute)
                                        .addComponent(jLabel4)
                                        .addComponent(txthargatiket)
                                        .addComponent(jLabel5)
                                        .addComponent(txtjumbel)
                                        .addComponent(pesawat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtjumhar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sejalan)
                                    .addComponent(jLabel8)
                                    .addComponent(pp)
                                    .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txttotalhart, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtroute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txthargatiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjumbel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtjumhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sejalan)
                                .addGap(34, 34, 34))
                            .addComponent(pp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotalhart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cash)
                    .addComponent(potbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kredit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ttlharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar)
                    .addComponent(btntotal)
                    .addComponent(btnjumlah))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesawatActionPerformed
                                       

    NumberFormat nf = NumberFormat.getInstance(new Locale("id", "ID"));

    if (pesawat.getSelectedItem().equals("Silahkan Pilih")) {
        txtroute.setText("");
        txthargatiket.setText("");
    } 

    if (pesawat.getSelectedItem().equals("Garuda")) {
        txtroute.setText("JKT-BALI");
        txthargatiket.setText("Rp " + nf.format(1000000));
    } 

    if (pesawat.getSelectedItem().equals("Merpati")) {
        txtroute.setText("JKT-LOMBOK");
        txthargatiket.setText("Rp " + nf.format(800000));
    } 

    if (pesawat.getSelectedItem().equals("Mandala")) {
        txtroute.setText("JKT-JATIM");
        txthargatiket.setText("Rp " + nf.format(700000));
    } 

    if (pesawat.getSelectedItem().equals("Lion")) {
        txtroute.setText("JKT-Medan");
        txthargatiket.setText("Rp " + nf.format(500000));
    } 

    if (pesawat.getSelectedItem().equals("Sempati")) {
        txtroute.setText("JKT-RIAU");
        txthargatiket.setText("Rp " + nf.format(850000));
    } 


    }//GEN-LAST:event_pesawatActionPerformed

    private void txtjumbelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumbelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumbelActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        
    }//GEN-LAST:event_ppActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjumlahActionPerformed
 String har = txthargatiket.getText().replace(".", "").replace("Rp", "").trim();
    totalhar = Integer.parseInt(har);

    // jumlah beli
    jumbel = Integer.parseInt(txtjumbel.getText());

    // multiplier berdasarkan radio button
    if (sejalan.isSelected()) {
        multi = 1;
    } else if (pp.isSelected()) {
        multi = 2;
    } else {
        multi = 1;
    }

    // hitung total
    total = totalhar * jumbel * multi;

    // diskon (PP dapat 10%, sejalan tidak dapat)
    if (pp.isSelected()) {
        diskon = total * 0.1;
    } else {
        diskon = 0;
    }

    // format angka + Rp
    NumberFormat nf = NumberFormat.getInstance(new Locale("id", "ID"));

    txtjumhar.setText("Rp " + nf.format(total));
    txtdiskon.setText("Rp " + nf.format(diskon));

    totalbayar = total - diskon;
    txttotalhart.setText("Rp " + nf.format(totalbayar));    }//GEN-LAST:event_btnjumlahActionPerformed

    private void sejalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sejalanActionPerformed
     
    }//GEN-LAST:event_sejalanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        txtroute.setText(" ");
        txtjumhar.setText(" ");
        txthargatiket.setText(" ");
        txtjumbel.setText(" ");
        txtdiskon.setText(" ");
        txttotalhart.setText(" ");
        
        // reset radio button
    buttonGroup1.clearSelection();

    // reset combobox
    pesawat.setSelectedIndex(0);
    
    buttonGroup2.clearSelection();

    // reset variabel global
    total = 0;
    totalhar = 0;
    jumbel = 0;
    multi = 1;
    diskon = 0;
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
                                

    // ambil total bayar yang sudah diformat
    String har = txttotalhart.getText().replace(".", "").replace("Rp", "").trim();
    hk = Integer.parseInt(har);

    // diskon metode pembayaran
    if (cash.isSelected()) {
        discont = 0.05; // cash diskon 5%
    } else if (kredit.isSelected()) {
        discont = 0; // kredit tanpa diskon
    } else {
        discont = 0;
    }

    // hitung potongan
    ttldsc = hk * discont;

    NumberFormat nf = NumberFormat.getInstance(new Locale("id", "ID"));
    potbayar.setText("Rp " + nf.format(ttldsc));

    // total akhir setelah potongan
    hs = hk - ttldsc;
    ttlharga.setText("Rp " + nf.format(hs));

    }//GEN-LAST:event_btntotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnjumlah;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btntotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton kredit;
    private javax.swing.JComboBox<String> pesawat;
    private javax.swing.JTextField potbayar;
    private javax.swing.JRadioButton pp;
    private javax.swing.JRadioButton sejalan;
    private javax.swing.JTextField ttlharga;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txthargatiket;
    private javax.swing.JTextField txtjumbel;
    private javax.swing.JTextField txtjumhar;
    private javax.swing.JTextField txtroute;
    private javax.swing.JTextField txttotalhart;
    // End of variables declaration//GEN-END:variables
}
